name: Referer Mod
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Selenium
        run: |
          pip install selenium
      - name: Build add-on archive
        run: |
          make dist
      - name: Build testenv container images
        run: |
          docker-compose build
        working-directory: testserver/
      - name: Start test environment
        run: |
          docker-compose up -d
        working-directory: testserver/
      - name: Run add-on test
        run: |
          python -u test.py
      - name: Stop test environment
        run: |
          docker-compose down
        working-directory: testserver/

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install ESLint
        run: npm install eslint
      - name: Run ESLint
        run: npx eslint .
