name: Test environment
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: testserver
    steps:
      - uses: actions/checkout@v2
      - name: Build container images
        run: |
          docker-compose build
      - name: Start test environment
        run: |
          docker-compose up -d
      - name: Check if proxy and servers work
        run: |
          curl -v --fail --output - --proxy http://localhost:8080 http://www.x.test/ http://site.y.test/ >/dev/null
      - name: Stop test environment
        run: |
          docker-compose down
